# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="4.1.*" DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp .env.dist .env
  - php bin/console doctrine:database:create
  - php bin/console make:migration
  - php bin/console --no-interaction doctrine:migrations:migrate
  - php bin/console --no-interaction doctrine:fixtures:load

# Run script
script:
  - phpunit

# After a build, send email notification with the build results
notifications:
  email: rhidja@gmail.com
